---
- name: Add ooblistener environment vars system-wide.
  ansible.builtin.lineinfile:
    path: /etc/profile.d/ooblistener.sh
    state: present
    regexp: "^DOMAIN="
    line: "DOMAIN={{ domain }}"
    create: true
    mode: '0644'
  become: true

- name: Stop resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: false
    state: stopped
  become: true

- name: Remove systemd's resolv.conf symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true

- name: Create regular file resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: touch
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Setup default DNS resolver
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: 'nameserver 8.8.8.8'
    line: 'nameserver 8.8.8.8'
  become: true

- name: Copy ooblister service file
  ansible.builtin.copy:
    src: ooblistener.service
    dest: /etc/systemd/system/ooblistener.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start ooblistener
  ansible.builtin.systemd_service:
    name: ooblistener
    enabled: true
    state: started
  become: true

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
    direction: incoming
  become: true
