---
- name: Add ooblistener environment vars system-wide.
  ansible.builtin.lineinfile:
    path: /etc/environment
    state: present
    regexp: "^DOMAIN="
    line: "DOMAIN={{ domain }}"
  become: true

- name: Stop resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: false
    state: stopped
  become: true

- name: Setup default DNS resolver
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: 'nameserver 127\.0\.0\.53'
    line: 'nameserver 8.8.8.8'
  become: true

- name: Copy ooblister service file
  ansible.builtin.copy:
    src: ooblistener.service
    dest: /etc/systemd/system/ooblistener.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start ooblistener
  ansible.builtin.systemd_service:
    name: ooblistener
    enabled: true
    state: started
  become: true
