repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
      - id: shfmt
      #- id: shellcheck

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
