---

- name: setup_cron
  hosts: all
  become: true
  gather_facts: false
  tasks: 
    - name: Update repositories cache and install "cron" package
      apt:
        name: cron
        state: present

    - name: Copy bash script
      ansible.builtin.copy:
        src:  ../files/bin/setup_https.sh
        dest: /opt/setup_https.sh
        owner: root
        group: root
        mode: '0544'
      
    - name: Create cronjob to generate TLS certificate when dns records have propagated
      ansible.builtin.cron:
        name: "check dirs"
        minute: "*/15"
        job: "/opt/setup_https.sh"
