---
 
- name: setup_xsshunterlite
  hosts: all
  gather_facts: false
  tasks:
    - name: Update repositories cache and install "apache/mod_wsgi" package
      apt:
        name: 
          - apache2
          - libapache2-mod-wsgi-py3
        state: present
      become: true
      
    - name: Install flask & flask_cors
      ansible.builtin.pip:
        name: 
          - flask
          - flask_cors
        state: latest
      become: true
     
    - name: Copy bash script
      ansible.builtin.copy:
        src:  ../files/bin/start_xsshunterlite.sh
        dest: /opt/start_xsshunterlite.sh
        owner: ubuntu
        group: ubuntu
        mode: '0544'
      become: true

    - name: Copy api source code
      ansible.builtin.copy:
        src: ../files/api/
        dest: /var/www/xsshunterlite/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      become: true
      
    - name: chmod xsshunterlite directory
      ansible.builtin.file:
        path: /var/www/xsshunterlite
        state: directory
        mode: '0777'

    - name: chmod notify_xss script
      ansible.builtin.file:
        path: /var/www/xsshunterlite/notify_xss.sh
        state: file
        mode: '0755'