---

- name: setup_interactsh
  hosts: all
  become: true
  gather_facts: false
  environment:
    GOPATH: "/usr/local/go"
    PATH: "/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin"
  tasks:       
    - name: Install interactsh-server
      command: go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-server@latest
      
    - name: Install interactsh-client
      command: go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest

    - name: Install anew
      command: go install -v github.com/tomnomnom/anew@latest

    - name: Install "curl" package
      apt: 
        name: 
          - curl
          - jq
        state: present

    - name: Copy subresources
      ansible.builtin.copy:
        src: ../files/www/
        dest: /opt/www/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      
    - name: Copy bash script
      ansible.builtin.copy:
        src:  ../files/bin/start_interactsh.sh
        dest: /opt/start_interactsh.sh
        owner: ubuntu
        group: ubuntu
        mode: '0544'
    
    - name: Copy ooblister service file
      ansible.builtin.copy:
        src:  ../files/conf/ooblistener.service
        dest: /etc/systemd/system/ooblistener.service
        owner: ubuntu
        group: ubuntu
        mode: '0644'
