---

- name: setup_golang
  hosts: all
  gather_facts: false
  vars:
    version: 1.21.7
    env: |
      export GOPATH=/usr/local/go/
      export PATH=$PATH:/usr/local/go/bin
  tasks:
    - name: Download go tar file
      command: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
      tags: golang
      
    - name: Extract and move new go folder to /usr/local
      command: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
      become: true
      tags: golang

    - name: Delete downloaded tar file
      shell: rm -rf go{{version}}.linux-amd64.tar.gz*
      
    - name: Add golang to system-wide $PATH.
      lineinfile:
        dest: /etc/bashrc
        line: "{{ env }}"
        regexp: "{{ env }}"
        state: present
        insertafter: EOF
      become: true
      tags: golang
      