---
- name: setup_cron
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update repositories cache and install "cron" package
      apt:
        name: cron
        state: present

    - name: Copy setup_https script
      ansible.builtin.copy:
        src: ../files/bin/setup_https.sh
        dest: /opt/setup_https.sh
        owner: root
        group: root
        mode: "0544"

    - name: Copy performance_report script
      ansible.builtin.copy:
        src: ../files/bin/performance_report.sh
        dest: /usr/bin/performance_report.sh
        owner: root
        group: root
        mode: "0544"

    - name: Create cronjob to generate TLS certificate when dns records have propagated
      ansible.builtin.cron:
        name: "check dirs"
        minute: "*/15"
        job: "/opt/setup_https.sh"

    - name: Create cronjob to send performance report
      ansible.builtin.cron:
        name: "performance report"
        minute: "0"
        hour: "10"
        job: "/usr/bin/performance_report.sh"

    - name: Create cronjob to reboot the server
      ansible.builtin.cron:
        name: "reboot server"
        weekday: "1"
        minute: "0"
        hour: "0"
        job: "/usr/sbin/reboot --reboot"
