---

- name: setup_notify
  hosts: all
  become: true
  gather_facts: false
  environment:
    GOPATH: "/usr/local/go"
    PATH: "$PATH:/usr/local/go/bin"
  tasks:       
    - name: Install notify
      command: go install -v github.com/projectdiscovery/notify/cmd/notify@latest

    - name: Create notify config directory
      ansible.builtin.file:
        path: /root/.config/notify/
        state: directory
        mode: '0444'
        
    - name: Copy notify config
      ansible.builtin.copy:
        src:  ../files/conf/provider-config.yaml
        dest: /opt/provider-config.yaml
        owner: root
        group: root
        mode: '0644'
      