---

- name: start_ooblistener
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Write domain name to file
      ansible.builtin.copy:
        content: "{{ domain }}"
        dest: /opt/domain.txt
        owner: ubuntu
        group: ubuntu
        mode: '0444'

    - name: stop resolved
      command: systemctl stop systemd-resolved

    - name: setup default DNS resolver
      command: sed -i 's/127.0.0.53/8.8.8.8/' /etc/resolv.conf
      
    - name: enable ooblistener
      command: systemctl enable ooblistener
      
    - name: start ooblistener
      command: systemctl start ooblistener
