---

- name: start_ooblistener
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Write domain name to file
      ansible.builtin.copy:
        content: "{{ domain }}"
        dest: /opt/domain.txt
        owner: root
        group: root
        mode: '0444'

    - name: stop resolved
      command: systemctl stop systemd-resolved
      
    - name: disable resolved
      command: systemctl disable systemd-resolved

    - name: setup default DNS resolver
      command: sed -i 's/127.0.0.53/8.8.8.8/' /etc/resolv.conf
      
    - name: Copy ooblister service file
      ansible.builtin.copy:
        src:  ../files/conf/ooblistener.service
        dest: /etc/systemd/system/ooblistener.service
        owner: root
        group: root
        mode: '0644'
      
    - name: enable ooblistener
      command: systemctl enable ooblistener
      
    - name: start ooblistener
      command: systemctl start ooblistener
