---
- name: Check installed tools
  ansible.builtin.shell: |
    . /etc/profile.d/golang.sh
    ls $GOPATH/bin
  register: gotools
  changed_when: false
  become: true

- name: Install interactsh-server
  ansible.builtin.shell: |
    . /etc/profile.d/golang.sh
    go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-server@latest
  when: '"interactsh-server" not in gotools.stdout_lines'
  changed_when: true
  become: true

- name: Install interactsh-client
  ansible.builtin.shell: |
    . /etc/profile.d/golang.sh
    go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest
  when: '"interactsh-client" not in gotools.stdout_lines'
  changed_when: true
  become: true

- name: Install anew
  ansible.builtin.shell: |
    . /etc/profile.d/golang.sh
    go install -v github.com/tomnomnom/anew@latest
  when: '"anew" not in gotools.stdout_lines'
  changed_when: true
  become: true

- name: Install impacket
  ansible.builtin.pip:
    name: impacket
    state: present
  become: true

- name: Install "curl" package
  ansible.builtin.package:
    name:
      - curl
      - jq
    state: present
  become: true

- name: Copy subresources
  ansible.builtin.copy:
    src: index.html
    dest: /opt/www/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Copy bash script
  ansible.builtin.copy:
    src: start_interactsh.sh
    dest: /opt/start_interactsh.sh
    owner: root
    group: root
    mode: "0544"
  become: true
