---
- name: Include variables.
  include_vars: main.yml

- name: Download go tar file
  get_url:
    url: https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
    dest: /tmp/go{{version}}.linux-amd64.tar.gz

- name: Extract and move new go folder to /usr/local
  command: tar -C /usr/local -xzf /tmp/go{{version}}.linux-amd64.tar.gz
  become: true

- name: Delete downloaded tar file
  command: rm -rf /tmp/go{{version}}.linux-amd64.tar.gz*

- name: Create golang system-wide environment file
  ansible.builtin.file:
    path: /etc/profile.d/golang.sh
    state: touch
    mode: "0644"
  become: true

- name: Add golang environment vars system-wide.
  lineinfile:
    path: /etc/profile.d/golang.sh
    state: present
    regexp: "^export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: true
