---
- name: Write domain name to file
  ansible.builtin.copy:
    content: "{{ domain }}"
    dest: /opt/domain.txt
    owner: root
    group: root
    mode: "0444"
  become: true

- name: Stop resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: false
    state: stopped
  become: true

- name: Setup default DNS resolver
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '127\.0\.0\.53'
    line: 8.8.8.8
  become: true

- name: Copy ooblister service file
  ansible.builtin.copy:
    src: ooblistener.service
    dest: /etc/systemd/system/ooblistener.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start ooblistener
  ansible.builtin.systemd_service:
    name: ooblistener
    enabled: true
    state: started
  become: true
