---
- name: Include variables.
  ansible.builtin.include_vars: main.yml

- name: Download go tar file
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz
    dest: /tmp/go{{ version }}.linux-amd64.tar.gz
    mode: 444

- name: Extract and move new go folder to /usr/local
  ansible.builtin.unarchive:
    src: /tmp/go{{ version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: true
    extra_opts:
      - --no-same-owner
  become: true

- name: Delete downloaded tar file
  ansible.builtin.file:
    path: /tmp/go{{ version }}.linux-amd64.tar.gz
    state: absent

- name: Add golang environment vars system-wide.
  ansible.builtin.lineinfile:
    path: /etc/profile.d/golang.sh
    state: present
    regexp: "^export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
    create: true
    mode: '0644'
  with_items: "{{ os_environment }}"
  become: true
