---
- name: Clean up apt sources
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: absent
  become: true

- name: Install python3-pip package
  ansible.builtin.package:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Symlink python3 to python
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: true

- name: Symlink pip3 to pip
  ansible.builtin.file:
    src: /usr/bin/pip3
    dest: /usr/bin/pip
    state: link
  failed_when: false
  become: true

- name: Install virtualenv & pipx
  ansible.builtin.pip:
    name:
      - virtualenv
      - pipx
    state: present
  become: true
