---
- name: Check installed tools
  ansible.builtin.shell: |
    . /etc/profile
    ls $GOPATH/bin
  register: gotools
  changed_when: false
  become: true

- name: Install dns-delay-server
  ansible.builtin.shell: |
    . /etc/profile
    go install github.com/intruder-io/dns-delay-server@latest
  when: '"dns-delay-server" not in gotools.stdout_lines'
  changed_when: true
  become: true

- name: Install rebind-server
  ansible.builtin.shell: |
    . /etc/profile
    go install github.com/intruder-io/rebind-server@latest
  when: '"rebind-server" not in gotools.stdout_lines'
  changed_when: true
  become: true

- name: Generate hex-string for matching specific subdomains in dns queries
  ansible.builtin.shell: |
    set -o pipefail
    . /etc/profile
    printf -- "-r`echo $DOMAIN | tr '.' '\n' | parallel 'printf "|%02d|{}" $(printf {}|wc -c)'`"
  register: hex_data
  changed_when: true
  failed_when: false
  become: true

- name: Add IPv4 PREROUTING rule
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: "# rules.before"
    block: |
      *nat
      -A PREROUTING -p udp --dport 53 -m string --hex-string "{{ hex_data.stdout_lines[0] }}" --algo bm -j DNAT --to-destination :5533
      COMMIT
  failed_when: false
  become: true

- name: Add IPv6 PREROUTING rule
  ansible.builtin.blockinfile:
    path: /etc/ufw/before6.rules
    insertbefore: "# rules.before"
    block: |
      *nat
      -A PREROUTING -p udp --dport 53 -m string --hex-string "{{ hex_data.stdout_lines[0] }}" --algo bm -j DNAT --to-destination :5533
      COMMIT
  failed_when: false
  become: true

- name: Realod ufw
  community.general.ufw:
    state: reloaded
  become: true
