---
- name: Update repositories cache and install "apache/mod_wsgi" package
  ansible.builtin.package:
    name:
      - apache2
      - libapache2-mod-wsgi-py3
      - sqlite3
    state: present
  become: true

- name: Install flask & flask_cors
  ansible.builtin.pip:
    name:
      - flask
      - flask_cors
    state: present
  become: true

- name: Copy bash script
  ansible.builtin.copy:
    src: start_exploit_srv.sh
    dest: /opt/start_exploit_srv.sh
    owner: root
    group: root
    mode: "0544"
  become: true

- name: Copy api source code
  ansible.builtin.copy:
    src: api/
    dest: /var/www/exploit_srv/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Chmod exploit_srv directory
  ansible.builtin.file:
    path: /var/www/exploit_srv
    state: directory
    mode: "0777"
  become: true

- name: Chmod notify wrapper script
  ansible.builtin.file:
    path: /var/www/exploit_srv/notify.sh
    state: file
    mode: "0755"
  become: true

- name: Setup cronjobs
  ansible.builtin.include_tasks:
    file: cron.yml
