name: build

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-snapshot:
    runs-on: macos-latest
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup pre-commit
        run: sudo pip3 install pre-commit

      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Run vagrant up
        run: vagrant up
