name: build

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-snapshot:
    runs-on: macos-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install dependencies.
        run: pip3 install pre-commit ansible molecule[docker] molecule-plugins[docker] docker yamllint ansible-lint

      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run Molecule tests.
        run: molecule --debug test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ubuntu2204
          DOCKER_HOST: "tcp://docker:2375"
