name: build

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install dependencies.
        run: pip3 install pre-commit ansible molecule[docker] molecule-plugins[docker] docker yamllint ansible-lint

      - name: Installing tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Installing shfmt
        run: |
          curl -o /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.9.0/shfmt_v3.9.0_linux_amd64
          chmod +x /usr/local/bin/shfmt

      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run Molecule converge
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ubuntu2204
