name: publish_snapshot

on:
  workflow_dispatch:

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: create AWS AMI
        run: chmod +x ./create_snapshot.sh ; ./create_snapshot.sh aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
